accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [
    path('register', views.RegisterView.as_view(), name='register'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('selfprofile', views.SelfProfileUserView.as_view(), name='selfprofile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

home/urls.py
from django.urls import path
from . import views
app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('detailpost/<int:pk>/<slug:slug>', views.DetailPostView.as_view(), name='detailpost'),
    path('addpost', views.AddPostUserView.as_view(), name='addpost'),
    path('update/<int:pk>',views.UpdatePostUserView.as_view(), name='update'),
    path('delete/<int:pk>/<slug:slug>',views.DetailPostView.as_view(), name='delete'),
    path('profiles/<int:pk>', views.UserProfile.as_view(), name='profiles'),
    path('folow/<int:pk>', views.FolowingUserView.as_view(), name='follow'),
    path('unfolow/<int:pk>', views.UnfollowUserView.as_view(), name='unfollow'),
    path('replaycomment/<int:pk>', views.AddReplayView.as_view(), name='replay'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    slug = models.SlugField(max_length=20, blank=True, null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.slug = slugify(self.title)
        super().save()

    def get_absolut_url(self):
        return reverse('home:detailpost', args=[self.pk, self.slug])


    def __str__(self):
        return f'{self.title} - {self.user.username}'

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'comments for post{self.post} by {self.user}'




class ReplayComments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='replays')
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replays')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'replay comment : {self.comment} in user {self.user}'



class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'like post{self.post} by user: {self.user}'

home/forms.py
from django import forms
from .models import Post

class AddUpdatePostUserForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body')

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import Post, Comment, ReplayComments
from accounts.models import RelationInstance
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import AddUpdatePostUserForm
from django.contrib.auth.models import User
from django.contrib import messages
class HomeView(View):
    def get(self, request):
        users = User.objects.all()
        return render(request, 'home/index.html', {'users': users})

class UserProfile(LoginRequiredMixin, View):
    def get(self, request, pk):
        is_following = False
        user = User.objects.get(pk=pk)
        relation = RelationInstance.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            is_following=True
        posts = Post.objects.filter(user=user.id)
        return render(request, 'home/userprofile.html', {'user': user, 'posts': posts, 'is_following': is_following})



class DetailPostView(LoginRequiredMixin,View):

    def get(self, request, pk, slug):
        post = Post.objects.get(pk=pk, slug=slug)
        commens = post.comments.all()
        return render(request, 'home/detailpost.html', {'post': post, 'comments': commens})

    def post(self, request, pk, slug):
        post = Post.objects.get(pk=pk, slug=slug)
        Comment.objects.create(user=request.user, post=post, body=request.POST['body'])
        return redirect('home:home')









class AddPostUserView(LoginRequiredMixin, View):
    form_class = AddUpdatePostUserForm
    template = 'home/addpostuser.html'
    def get(self, request):
        form = self.form_class()
        return render(request, self.template, {'form': form})
    def post(self, request):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            messages.success(request, 'added post', 'success')
            return redirect('accounts:selfprofile')
        return render(request, self.template, {'form': form})


class UpdatePostUserView(LoginRequiredMixin, View):
    form_class = AddUpdatePostUserForm
    template = 'home/updatepostuser.html'
    def setup(self, request, *args, **kwargs):
        self.instance = Post.objects.get(pk=kwargs['pk'])
        return super().setup(request,*args, **kwargs)

    def get(self, request, pk):
        form = self.form_class(instance=self.instance)
        return render(request, self.template, {'form': form})
    def post(self, request, pk):
        form = self.form_class(data=request.POST, instance=self.instance)
        if form.is_valid():
            form.save()
            messages.success(request, 'updated post', 'success')
            return redirect('accounts:selfprofile')
        return render(request, self.template, {'form': form})
class DeletePostUserView(LoginRequiredMixin, View):
    def get(self, request, pk, slug):
        post = Post.objects.get(pk=pk)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request, 'deleted post', 'success')
        else:
            messages.error(request, 'you are con not delete post', 'danger')
        return redirect('home:home')



class FolowingUserView(LoginRequiredMixin, View):
    def get(self, request, pk):
        user = User.objects.get(pk=pk)
        relation = RelationInstance.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            messages.error(request, 'you are not con following', 'danger')
            return redirect('home:profiles' , user.id)
        else:
            RelationInstance.objects.create(from_user=request.user, to_user=user)
            messages.success(request, 'follow','success')
            return redirect('home:profiles', user.id)


class UnfollowUserView(View):
    def get(self, request, pk):
        user = User.objects.get(pk=pk)
        relation = RelationInstance.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            relation.delete()
            messages.success(request, 'unfollow', 'success')
        else:
            messages.error(request, 'you are not follow', 'danger')
        return redirect('home:profiles', user.id)






class AddReplayView(LoginRequiredMixin, View):
    def get(self, request, pk):
        comment = Comment.objects.get(pk=pk)

        return render(request, 'home/replay.html', {'comment': comment})
    def post(self, request, pk):
        comment = Comment.objects.get(pk=pk)
        if request.POST.get('body') is not None:
            ReplayComments.objects.create(user=request.user, comment=comment, body=request.POST['body'])
            messages.success(request, 'add replay', 'success')
            return redirect('home:home')
        return render(request, 'home/replay.html', {'comment': comment})

home/templates/home/addpostuser.html
{% extends 'include/base.html' %}
{% block content %}

    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
        <button class="btn btn-dark"> add post </button>
    </form>


{% endblock content %}

home/templates/home/detailpost.html
{% extends 'include/base.html' %}
{% block content %}

    <a href="{% url 'home:update' post.id %}"><button class="btn btn-info">update</button></a>
    <a href="{% url 'home:delete' post.id post.slug %}"><button class="btn btn-danger">delete</button></a>
    <h6>user :{{ post.user.username }}</h6>
    <h6>title: {{ post.title }}</h6>
    <p>{{ post.body }}</p>
    <h6> comments:</h6>
    {% for comment in comments %}
        <a href="{% url 'home:profiles' comment.user.id %}"> comments by {{ comment.user }}</a>
        <br>
        <a class="btn-dark" href="{% url 'home:replay' comment.id %}"> replay </a>

        <p> {{ comment.body }}</p>
        <br>
        {% if comment.replays %}
            {% for replay in comment.replays.all %}
                <h6> user: {{ replay.user }} </h6>
                <p> {{ replay.body }} </p>
            {% endfor %}
        {% endif %}
    {% endfor %}
<form method="post">
{% csrf_token %}
  <textarea id="bodey" name="body" rows="4" cols="50" placeholder="body ..."></textarea>
  <br>
  <input type="submit" value="Submit">
</form>


{% endblock content %}

home/templates/home/index.html
{% extends 'include/base.html' %}

{% block content %}
    {% include 'include/message.html' %}
    <h3> users of mini </h3>
    {% if request.user.is_authenticated %}
        {% for user in users %}
            <a class="page-item" href="{% url 'home:profiles' user.id %}"> {{ user.username }}</a>
            <br>
        {% endfor %}
    {% endif %}

    {% if request.user.is_authenticated %}
        <center>
    {% else %}
    <a class="submit-row" href="{% url 'accounts:register' %}"> register </a>
    {% endif %}

{% endblock content %}

home/templates/home/replay.html
{% extends 'include/base.html' %}
{% block content %}

    <h6>user :{{ comment.user }}</h6>
    <p> {{ comment.body }} </p>

    <form method="post">
{% csrf_token %}
  <textarea id="bodey" name="body" rows="4" cols="50" placeholder="body ..."></textarea>
  <br>
  <input type="submit" value="Submit">
</form>





{% endblock %}

home/templates/home/updatepostuser.html
{% extends 'include/base.html' %}
{% block content %}

    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
        <button class="btn btn-info"> update </button>
    </form>


{% endblock content %}

home/templates/home/userprofile.html
{% extends 'include/base.html' %}
{% block content %}
{% if request.user.id != user.id and not is_following %}
    <a href="{% url 'home:follow' user.id %}"> follow </a>
{% elif request.user.id != user.id and  is_following %}
    <a href="{% url 'home:unfollow' user.id %}">unfollow</a>
    {% endif %}

    <h6> username:{{ user.username }}</h6>
    {% for post in posts %}
        <a href="{% url 'home:detailpost' post.id  post.slug %}">{{ post.title }}</a>
        <br>
    {% endfor %}


{% endblock content %}