accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [
    path('register', views.RegisterView.as_view(), name='register'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('selfprofile', views.SelfProfileUserView.as_view(), name='selfprofile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

home/urls.py
from django.urls import path
from . import views
app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('detailpost/<int:pk>/<slug:slug>', views.DetailPostView.as_view(), name='detailpost'),
    path('addpost', views.AddPostUserView.as_view(), name='addpost'),
    path('update/<int:pk>',views.UpdatePostUserView.as_view(), name='update'),
    path('delete/<int:pk>/<slug:slug>',views.DetailPostView.as_view(), name='delete'),
    path('profiles/<int:pk>', views.UserProfile.as_view(), name='profiles'),
    path('folow/<int:pk>', views.FolowingUserView.as_view(), name='follow'),
    path('unfolow/<int:pk>', views.UnfollowUserView.as_view(), name='unfollow'),
    path('replaycomment/<int:pk>', views.AddReplayView.as_view(), name='replay'),
]

templates/include/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Bare - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body>
<!-- Responsive navbar-->
{% include 'include/navbar.html' %}
<!-- Page content-->
<div class="container">
    {% block content %}


    {% endblock content %}

</div>        <!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

templates/include/message.html
{% if messages %}
    {% for m in messages %}
        <h6>  {{ m }} </h6>
    {% endfor %}
{% endif %}

templates/include/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home:home' %}">mini</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page"
                                        href="{% url 'home:home' %}">Home</a></li>
                <br>
                {% if request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">logout</a>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:selfprofile' %}">your profile</a>
                    </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>