accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [
    path('register', views.RegisterView.as_view(), name='register'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('selfprofile', views.SelfProfileUserView.as_view(), name='selfprofile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

home/urls.py
from django.urls import path
from . import views
app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('detailpost/<int:pk>/<slug:slug>', views.DetailPostView.as_view(), name='detailpost'),
    path('addpost', views.AddPostUserView.as_view(), name='addpost'),
    path('update/<int:pk>',views.UpdatePostUserView.as_view(), name='update'),
    path('delete/<int:pk>/<slug:slug>',views.DetailPostView.as_view(), name='delete'),
    path('profiles/<int:pk>', views.UserProfile.as_view(), name='profiles'),
    path('folow/<int:pk>', views.FolowingUserView.as_view(), name='follow'),
    path('unfolow/<int:pk>', views.UnfollowUserView.as_view(), name='unfollow'),
    path('replaycomment/<int:pk>', views.AddReplayView.as_view(), name='replay'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class RelationInstance(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.from_user} following {self.to_user}'

accounts/forms.py
from django import forms
from  django.contrib.auth.models import User
from django.core.validators import ValidationError
class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
        'placeholder': 'enter  username'})
    )
    email = forms.CharField(widget=forms.EmailInput(
        attrs={'class': 'form-control',
        'placeholder': 'enter your email'})
    )
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control','placeholder': 'enter your password'}))
    password2 = forms.CharField(label='respect pssword' ,widget=forms.PasswordInput(
        attrs={'class': 'form-control','placeholder': 'enter your password'}))

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')
        if password and password2:
            if password != password:
                raise ValidationError('password no match')

    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username).exists()
        if user:
            raise ValidationError('username is invalid')
        return username
    def clean_email(self):
        email = self.cleaned_data['email']
        email_user =  User.objects.filter(email=email).exists()
        if email_user:
            raise ValidationError('email is invalid')
        return email


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
        'placeholder': 'enter  username'})
    )
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control',
               'placeholder': 'enter your password'})
    )
    # def clean(self):
    #     cleaned_data = super().clean()
    #     username = User.objects.filter(username=cleaned_data.get('username')).exists()
    #     email = User.objects.filter(email=cleaned_data.get('username')).exists()
    #     if username is not True:
    #         raise ValidationError('username or email is not valid')
    #
    #

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib import messages
from .forms import RegisterForm, LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from home.models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views

class RegisterView(View):
    form_class = RegisterForm
    template = 'accounts/register.html'

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        if user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    def get(self, request):
        form = self.form_class()
        return render(request, self.template, {'form': form})
    def post(self, request):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            cd =form.cleaned_data
            User.objects.create_user(username=cd['username'], email=cd['email'], password=cd['password'])
            messages.success(request, 'register successfuly', 'success')
            return redirect('home:home')
        return render(request, self.template, {'form': form})


class LoginView(View):
    form_class = LoginForm
    template = 'accounts/login.html'

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        if user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    def get(self, request):
        form = self.form_class()
        return render(request, self.template, {'form': form})

    def post(self, request):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,username=cd['username'], password=cd['password'])
            login(request, user)
            messages.success(request, 'you are logined', 'success')
            return redirect('home:home')
        return render(request, self.template, {'form': form})



class LogoutView(LoginRequiredMixin,View):
    
    def get(self, request):
        logout(request)
        messages.success(request, 'you are logouted', 'success')
        return redirect('home:home')



class SelfProfileUserView(View):
    template = 'accounts/selfprofile.html'
    def get(self, request):
        user = request.user
        posts = Post.objects.filter(user=user.id)
        return render(request, self.template, {'user': user, 'posts': posts})

class UserPasswordResetView(auth_views.PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'


class UserPasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class UserPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class UserPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'

accounts/templates/accounts/login.html
{% extends 'include/base.html' %}

{% block content %}
    <form class="align-content-center" method="post">
        {% csrf_token %}
        {{ form.as_p }}

    <button class="submit-row">login</button>
    </form>

{% endblock content %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
  <p>your password changed.</p>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
    {% if validlink %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Change">
    </form>
    {% else %}
        <p>this link is not valid. please try again.</p>
    {% endif %}
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
  <p>we sent you an email.</p>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:

{{ protocol}}://{{ domain }}{% url 'account:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    </form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'include/base.html' %}

{% block content %}
    <form class="align-content-center" method="post">
        {% csrf_token %}
        {{ form.as_p }}

    <button class="submit-row">submit</button>
    </form>
{% endblock content %}

accounts/templates/accounts/selfprofile.html
{% extends 'include/base.html' %}
{% block content %}

    <h5>{{ user.username }}</h5>
    <a href="{% url 'home:addpost' %}"> <button class="btn btn-primary"> add post </button></a>
        {% for post in posts %}
            <h6><a href="{{post.get_absolut_url}}">{{ post.title }}</a></h6>
        {% endfor %}


{% endblock content %}